id: FrozenLakeTab-v0
max_steps_per_ep: 200
eval_episodes: 50
env_kwargs:
  map_name: "8x8"     # or "4x4", or provide 'desc:' list
  is_slippery: true
  step_cost: 0.0
  hole_penalty: 0.0
  goal_reward: 1.0